Repository GSG-G7/Parent-assistent, pull requests merged in 2019-09, with the labels that each got.

#6 Refactor README.md
  README.md
Labels: Done

#45 add main file sturcture - react setup - eslint-configurations
  .gitignore
  client/.gitignore
  client/eslintrc.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/Components/App/App.css
  client/src/Components/App/App.js
  client/src/Components/CommonComponent/Button/Button.css
  client/src/Components/CommonComponent/Button/Button.js
  client/src/Components/CommonComponent/Card/Card.css
  client/src/Components/CommonComponent/Card/Card.js
  client/src/Components/CommonComponent/Footer/Footer.css
  client/src/Components/CommonComponent/Footer/Footer.js
  client/src/Components/CommonComponent/Header/Header.css
  client/src/Components/CommonComponent/Header/Header.js
  client/src/Components/CommonComponent/Input/Input.css
  client/src/Components/CommonComponent/Input/Input.js
  client/src/Components/CommonComponent/Menu/Menu.css
  client/src/Components/CommonComponent/Menu/Menu.js
  client/src/Components/CommonComponent/Table/Table.css
  client/src/Components/CommonComponent/Table/Table.js
  client/src/Components/Pages/Activities/Activities.css
  client/src/Components/Pages/Activities/Activities.js
  client/src/Components/Pages/Home/Home.css
  client/src/Components/Pages/Home/Home.js
  client/src/Components/Pages/HomeWork/HomeWork.css
  client/src/Components/Pages/HomeWork/HomeWork.js
  client/src/Components/Pages/LogIn/LogIn.css
  client/src/Components/Pages/LogIn/LogIn.js
  client/src/Components/Pages/ParentProfile/ParentProfile.css
  client/src/Components/Pages/ParentProfile/ParentProfile.js
  client/src/Components/Pages/SignUp/SignUp.css
  client/src/Components/Pages/SignUp/SignUp.js
  client/src/Components/Pages/SignUpParent/SignUpParent.css
  client/src/Components/Pages/SignUpParent/SignUpParent.js
  client/src/Components/Pages/StudentProfile/StudentProfile.css
  client/src/Components/Pages/StudentProfile/StudentProfile.js
  client/src/Components/Pages/Subject/Subject.css
  client/src/Components/Pages/Subject/Subject.js
  client/src/Components/Pages/TeacherProfile/TeacherProfile.css
  client/src/Components/Pages/TeacherProfile/TeacherProfile.js
  client/src/index.css
  client/src/index.js
  client/src/serviceWorker.js
  package-lock.json
  package.json
Labels: awaiting review

#47 create common component footer
  client/src/Components/App/App.js
  client/src/Components/CommonComponent/Footer/Footer.css
  client/src/Components/CommonComponent/Footer/Footer.js
Labels: awaiting review

#50 create button component
  client/package-lock.json
  client/src/Components/CommonComponent/Button/Button.css
  client/src/Components/CommonComponent/Button/Button.js
  package.json
Labels: awaiting review

#55 Add db schema to readme
  README.md
  client/src/Components/CommonComponent/Button/index.js
  client/src/Components/CommonComponent/Footer/index.js
  client/src/Components/CommonComponent/Input/index.css
  client/src/Components/CommonComponent/Input/index.js
  client/src/index.js
Labels: awaiting review

#48 write Menu component js and css
  client/src/Components/CommonComponent/Menu/index.css
  client/src/Components/CommonComponent/Menu/index.js
Labels: awaiting review

#58 add some edits to input common component
  client/src/Components/CommonComponent/Input/index.css
  client/src/Components/CommonComponent/Input/index.js
Labels: awaiting review

#51 30 common component header
  client/.eslintrc.js
  client/src/Components/CommonComponent/Header/index.css
  client/src/Components/CommonComponent/Header/index.js
  client/src/Components/CommonComponent/Menu/index.css
  client/src/Components/CommonComponent/Menu/index.js
  client/src/assets/logo.png
Labels: awaiting review

#60 basic style for all pages
  client/src/Components/App/index.css
Labels: awaiting review

#59 Card component with its style file
  client/src/Components/CommonComponent/Card/index.css
  client/src/Components/CommonComponent/Card/index.js
Labels: awaiting review

#64 34 create student table
  client/src/Components/CommonComponent/Table/data.js
  client/src/Components/CommonComponent/Table/index.css
  client/src/Components/CommonComponent/Table/index.js
Labels: awaiting review

#65 add container , header and footer to the App
  client/src/Components/App/index.css
  client/src/Components/App/index.js
  client/src/Components/CommonComponent/Header/index.css
  client/src/Components/CommonComponent/Menu/index.css
  client/src/index.js
Labels: awaiting review

#66 62 create parent table
  client/src/Components/CommonComponent/StudentTable/data.js
  client/src/Components/CommonComponent/StudentTable/index.css
  client/src/Components/CommonComponent/StudentTable/index.js
  client/src/Components/CommonComponent/Table/data.js
  client/src/Components/CommonComponent/Table/index.js
  client/src/Components/CommonComponent/TeacherTable/data.js
  client/src/Components/CommonComponent/TeacherTable/index.css
  client/src/Components/CommonComponent/TeacherTable/index.js
Labels: awaiting review

#69 edit files names due to naming conventions
  client/eslintrc.js
  client/src/components/App/index.css
  client/src/components/App/index.js
  client/src/components/common/Button/index.css
  client/src/components/common/Button/index.js
  client/src/components/common/Card/index.css
  client/src/components/common/Card/index.js
  client/src/components/common/Footer/index.css
  client/src/components/common/Footer/index.js
  client/src/components/common/Header/index.css
  client/src/components/common/Header/index.js
  client/src/components/common/Input/index.css
  client/src/components/common/Input/index.js
  client/src/components/common/Menu/index.css
  client/src/components/common/Menu/index.js
  client/src/components/common/StudentTable/data.js
  client/src/components/common/StudentTable/index.css
  client/src/components/common/StudentTable/index.js
  client/src/components/common/TeacherTable/data.js
  client/src/components/common/TeacherTable/index.css
  client/src/components/common/TeacherTable/index.js
  client/src/components/pages/Activities/index.css
  client/src/components/pages/Activities/index.js
  client/src/components/pages/Home/index.css
  client/src/components/pages/Home/index.js
  client/src/components/pages/HomeWork/index.css
  client/src/components/pages/HomeWork/index.js
  client/src/components/pages/LogIn/index.css
  client/src/components/pages/LogIn/index.js
  client/src/components/pages/ParentProfile/index.css
  client/src/components/pages/ParentProfile/index.js
  client/src/components/pages/SignUp/index.css
  client/src/components/pages/SignUp/index.js
  client/src/components/pages/SignUpParent/index.css
  client/src/components/pages/SignUpParent/index.js
  client/src/components/pages/StudentProfile/index.css
  client/src/components/pages/StudentProfile/index.js
  client/src/components/pages/Subject/index.css
  client/src/components/pages/Subject/index.js
  client/src/components/pages/TeacherProfile/index.css
  client/src/components/pages/TeacherProfile/index.js
  client/src/index.js
Labels: awaiting review

#70 21 student profile
  client/src/components/App/index.css
  client/src/components/common/StudentTable/index.css
  client/src/components/common/TeacherTable/index.css
  client/src/components/common/TeacherTable/index.js
  client/src/components/pages/StudentProfile/index.css
  client/src/components/pages/StudentProfile/index.js
Labels: awaiting review

#72 write signUp component with its style && edit style for button component
  client/package-lock.json
  client/src/components/App/index.css
  client/src/components/common/Button/index.css
  client/src/components/pages/SignUp/index.css
  client/src/components/pages/SignUp/index.js
Labels: awaiting review

#75 Pages | Activities - page
  client/src/components/common/Card/data.js
  client/src/components/common/Card/index.css
  client/src/components/common/Card/index.js
  client/src/components/pages/Activities/index.css
  client/src/components/pages/Activities/index.js
Labels: awaiting review

#73 make simple home page
  client/src/assets/home__class.jpg
  client/src/assets/home__img.jpg
  client/src/components/common/Button/index.css
  client/src/components/common/Button/index.js
  client/src/components/common/Header/index.css
  client/src/components/common/Menu/index.css
  client/src/components/pages/Home/index.css
  client/src/components/pages/Home/index.js
Labels: awaiting review

#74 17 login
  client/package-lock.json
  client/package.json
  client/src/components/common/Input/index.css
  client/src/components/common/Input/index.js
  client/src/components/pages/LogIn/index.css
  client/src/components/pages/LogIn/index.js
  client/src/components/pages/utils/loginSchema.js
Labels: awaiting review

#80 25 error page
  client/src/components/pages/Error/index.css
  client/src/components/pages/Error/index.js
Labels: awaiting review

#81 Student subject
  client/src/components/pages/Subject/index.css
  client/src/components/pages/Subject/index.js
Labels: awaiting review

#78 write page TeacherProfile with its style and teacher image
  client/src/assets/teacher.jpg
  client/src/components/pages/TeacherProfile/fakeData.js
  client/src/components/pages/TeacherProfile/index.css
  client/src/components/pages/TeacherProfile/index.js
Labels: awaiting review

#86 remove properties into state
  client/src/components/common/Header/index.js
Labels: awaiting review

#82 validation schema | sign-up form
  client/src/components/common/Button/index.css
  client/src/components/common/Input/index.css
  client/src/components/pages/LogIn/index.css
  client/src/components/pages/LogIn/index.js
  client/src/components/pages/SignUpParent/index.css
  client/src/components/pages/SignUpParent/index.js
  client/src/components/pages/utils/signUpValidation.js
Labels: awaiting review

#84 24-make Homework component
  client/src/components/pages/HomeWork/data.js
  client/src/components/pages/HomeWork/index.css
  client/src/components/pages/HomeWork/index.js
Labels: awaiting review

#85 26 server file structure
  .eslintrc.json
  .travis.yml
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
  server/controllers/middlewares/.gitkeep
  server/controllers/routes/.gitkeep
  server/controllers/utils/.gitkeep
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/quieres/.gitkeep
  server/index.js
  server/router/index.js
  server/utils/.gitkeep
  test/index.test.js
  test/quieres/index.test.js
  test/routes/index.test.js
Labels: awaiting review

#79 add prop-types
  client/.eslintrc.js
  client/package.json
  client/src/components/common/Button/index.js
  client/src/components/common/Header/index.js
  client/src/components/common/Input/index.js
  client/src/components/common/Menu/index.js
  client/src/components/pages/Error/index.js
  client/src/components/pages/Subject/index.js
  package-lock.json
Labels: in progress

#88 9-database Schema
  .gitignore
  .travis.yml
  server/database/config/build.sql
Labels: awaiting review

#89 16 database config
  .gitignore
  server/database/config/build.js
  server/database/config/connection.js
  server/database/config/fakedata.sql
  test/quieres/index.test.js
  test/routes/index.test.js
Labels: awaiting review

#91 logout route
  package.json
  server/app.js
  server/controllers/index.js
  server/controllers/routes/logout.js
  server/router/index.js
  test/index.test.js
  test/routes/index.test.js
  test/routes/logout.test.js
Labels: awaiting review

#96 95- Auth middleware
  package-lock.json
  server/app.js
  server/controllers/middlewares/auth.js
  server/controllers/middlewares/index.js
  server/router/index.js
  test/routes/cookie.test.js
  test/routes/logout.test.js
Labels: awaiting review

#90 login-route
  package-lock.json
  server/controllers/index.js
  server/controllers/middlewares/auth.js
  server/controllers/routes/login.js
  server/controllers/routes/logout.js
  server/controllers/utils/loginSchema.js
  server/database/config/connection.js
  server/database/config/fakedata.sql
  server/database/quieres/login.js
  server/router/index.js
  test/quieres/index.test.js
  test/quieres/login.js
  test/routes/index.test.js
  test/routes/login.test.js
Labels: awaiting review
